import { test, expect } from '@playwright/test'
const navigate = async (page, desktop, mobile) => {
  const button = page.getByRole('button', { name: desktop, exact: true })
  await (await button.isVisible() ? button : page.getByRole('button', { name: mobile, exact: true })).click()
}
test.beforeEach(async ({ page }) => { await page.goto('/design-preview.html') })
test('clears composer immediately, scrolls to latest and restores failed sends', async ({ page }) => {
  const input = page.getByRole('textbox', { name: 'Tulis pesan' })
  await input.fill('uji kirim')
  await page.getByRole('button', { name: 'Kirim', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.getByText('Pesan contoh diterima: “uji kirim”.', { exact: false })).toBeVisible()
  const gap = await page.locator('.chat-scroll-inset').evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)
  expect(gap).toBeLessThan(100)
  await input.fill('uji gagal kirim')
  await page.getByRole('button', { name: 'Kirim', exact: true }).click()
  await expect(input).toHaveValue('uji gagal kirim')
})
test('manual balance adjustment, read-only history and Escape work in dark mode', async ({ page }) => {
  await page.getByRole('button', { name: 'Aktifkan mode gelap' }).click()
  await navigate(page, 'Dompet', 'wallets')
  await page.getByRole('button', { name: /aksi.*Tunai/i }).click()
  await page.getByRole('menuitem', { name: 'Sesuaikan saldo' }).click()
  const dialog = page.getByRole('dialog', { name: 'Sesuaikan saldo', exact: true })
  await dialog.getByRole('spinbutton').fill('400000.01')
  await dialog.getByRole('button', { name: /Tinjau/ }).click()
  await expect(dialog).toContainText('400.000,01')
  await dialog.getByRole('button', { name: /Konfirmasi/ }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText(/400\.000,01/).filter({ visible: true }).first()).toBeVisible()
  await page.getByRole('button', { name: /aksi.*Tunai/i }).click()
  await page.getByRole('menuitem', { name: 'Riwayat penyesuaian' }).click()
  const history = page.getByRole('dialog', { name: 'Riwayat penyesuaian Tunai' })
  await expect(history).toContainText('tidak dihitung sebagai pemasukan')
  await page.keyboard.press('Escape')
  await expect(history).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('report failure does not show zero balances and retry restores data', async ({ page }) => {
  await page.goto('/design-preview.html?reportError=1')
  await navigate(page, 'Laporan keuangan', 'analytics')
  await expect(page.getByText('Laporan belum bisa dimuat')).toBeVisible()
  await page.getByRole('button', { name: 'Coba lagi', exact: true }).click()
  await expect(page.getByText('Laporan belum bisa dimuat')).not.toBeVisible()
  await expect(page.getByText('Laporan seluruh transaksi tercatat', { exact: false })).toBeVisible()
})
